# Generated by Django 3.1.4 on 2021-04-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doe_computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('ram_type', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('Other', 'Other')], max_length=50)),
                ('hdd', models.CharField(max_length=50)),
                ('hdd_type', models.CharField(choices=[('SATA', 'SATA'), ('SSD', 'SSD'), ('Other', 'Other')], max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('monitor', models.CharField(max_length=50)),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('anti_viruse', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doe_copier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=50)),
                ('company_phone', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doe_Fiber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('line_code', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('support', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doe_printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=50)),
                ('Cartridge_number', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doe_projector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doe_Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('ssid', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('l_level', models.CharField(choices=[('1', 'الاول الاساسي'), ('2', 'الثاني الاساسي'), ('3', 'الثالث الاساسي'), ('4', 'الرابع الاساسي'), ('5', 'الخامس الاساسي'), ('6', ' السادس الاساسي'), ('7', 'السابع الاساسي'), ('8', 'الثامن الاساسي'), ('9', 'التاسع الاساسي'), ('10', 'العاشر الاساسي'), ('11', 'الحادي عشر'), ('12', 'الثاني عشر')], max_length=50)),
                ('u_level', models.CharField(choices=[('1', 'الاول الاساسي'), ('2', 'الثاني الاساسي'), ('3', 'الثالث الاساسي'), ('4', 'الرابع الاساسي'), ('5', 'الخامس الاساسي'), ('6', ' السادس الاساسي'), ('7', 'السابع الاساسي'), ('8', 'الثامن الاساسي'), ('9', 'التاسع الاساسي'), ('10', 'العاشر الاساسي'), ('11', 'الحادي عشر'), ('12', 'الثاني عشر')], max_length=50)),
                ('type', models.CharField(choices=[('ذكور', 'ذكور'), ('إناث', 'إناث'), ('مختلط', 'مختلط')], max_length=50)),
                ('st_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('principal', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('A', 'منطقة أ'), ('B', 'منطقة ب'), ('C', 'منطقة ج')], default='منطقة أ', max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.BooleanField(default=False)),
                ('area', models.IntegerField()),
                ('internet_connection', models.BooleanField(default=False)),
                ('teacher', models.CharField(max_length=50)),
                ('teacher_load', models.CharField(max_length=20)),
                ('projector', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='School_computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('hdd', models.CharField(max_length=20)),
                ('internet', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.school_lab')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.school')),
            ],
        ),
    ]
