# Generated by Django 3.1.4 on 2020-12-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doe_computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('barnd_name', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('hdd', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('monitor', models.CharField(max_length=50)),
            ],
        ),
    ]
