# Generated by Django 3.1.4 on 2021-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doe_computer',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
