# Generated by Django 3.1.4 on 2020-12-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201214_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doe_printer',
            old_name='Cartege_number',
            new_name='Cartridge_number',
        ),
    ]
