# Generated by Django 3.1.4 on 2021-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210506_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doe_computer',
            name='employee_name',
            field=models.CharField(choices=[('الادارة', 'الادارة'), ('التخطيط', 'التخطيط'), ('الشؤون الادارية', 'الشؤون الادارية'), ('الرقابة', 'الرقابة'), ('العلاقات العامة', 'العلاقات العامة'), ('الاشراف', 'الاشراف'), ('النواب', 'النواب'), ('الارشاد', 'الارشاد'), ('التعليم المهني', 'التعليم المهني'), ('الابنية', 'الابنية'), ('الامتحانات', 'الامتحانات'), ('المالية', 'المالية'), ('التعليم العام', 'التعليم العام'), ('الانشطة الطلابية', 'الانشطة الطلابية'), ('التقنيات التربوية', 'التقنيات التربوية'), ('اللوازم', 'اللوازم'), ('الديوان', 'الديوان'), ('الديوان', 'الديوان'), ('الصحة المدرسية', 'الصحة المدرسية'), ('الكتب', 'الكتب'), ('أخرى', 'أخرى')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doe_computer',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
